defmodule SanbaseWeb.Graphql.ProjectApiSocialVolumeQuery do
  use SanbaseWeb.ConnCase, async: false

  import Sanbase.Factory

  alias Sanbase.Project

  test "autogenerated query contains lowercased project name, slug and ticker" do
    p = insert(:random_erc20_project)
    query = Project.SocialVolumeQuery.default_query(p)

    assert query ==
             ~s|"#{String.downcase(p.ticker)}" OR "#{String.downcase(p.name)}" OR "#{String.downcase(p.slug)}"|
  end

  test "autogenerated query does not contain some common words" do
    p = insert(:project, %{name: "SomeName", ticker: "MAN", slug: "then"})
    query = Project.SocialVolumeQuery.default_query(p)
    assert query == ~s|"somename"|
  end
end
