FROM hexpm/elixir:1.17.2-erlang-26.2.5.2-debian-bullseye-20240701-slim

RUN apk add --no-cache make \
    g++ \
    git \
    postgresql-client \
    nodejs \
    nodejs-npm \
    inotify-tools \
    imagemagick \
    openssl \
    wget \
    rust \
    cargo

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install hex phx_new 1.6.14

#RUN mix format --check-formatted

WORKDIR /app
