version: "3.4"
services:
  postgres:
    image: postgres:10.10-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: santiment

  clickhouse-server:
    image: yandex/clickhouse-server:20.8.11.17
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  sanbase:
    build:
      context: .
      dockerfile: Dockerfile-dev

    volumes:
      - ./:/app:delegated

    hostname: sanbase_host

    command: sh -c "elixir --sname sanbase --cookie sanbase -S mix phx.server"
    expose:
      - 4000
    ports:
      - "4000:4000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/santiment
      ADMIN_BASIC_AUTH_USERNAME: admin
      ADMIN_BASIC_AUTH_PASSWORD: admin
      WEBSITE_URL: http://localhost:4000
      PUBLIC_URL: http://localhost:4000
      PARITY_URL: http://parity.stage.san:30954
      TECH_INDICATORS_URL: http://tech-indicators.default.svc.cluster.local
      CLICKHOUSE_DATABASE_URL: clickhouse://clickhouse-proxy.default.svc.cluster.local:8123/default
