FROM elixir:1.10.3-alpine

RUN apk add --no-cache make \
                       g++ \
                       git \
                       postgresql-client \
                       nodejs \
                       nodejs-npm \
                       inotify-tools \
                       imagemagick \
                       openssl \
                       wget

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

#RUN mix format --check-formatted

WORKDIR /app
