defmodule SanbaseWeb.DeepResearchShareLive do
  @moduledoc """
  Read-only public view of a shared deep research session.

  Reachable by any logged-in user on the admin pod (`/deep_research/shared/:id`
  — authentication is the router's concern, no admin-panel role required). Only
  sessions with `is_public: true` resolve; everything else renders the same
  "not available" state so a session id never leaks whether it exists.
  """
  use SanbaseWeb, :live_view

  import SanbaseWeb.DeepResearch.Components, only: [turn_view: 1]

  alias Sanbase.DeepResearch.Sessions

  @impl true
  def mount(%{"id" => id}, _session, socket) do
    case Sessions.get_public_session(id) do
      {:ok, %{session: session, turns: turns}} ->
        # Only the fields the page shows — keeps thread_id and the owner's
        # user_id off a publicly reachable page's assigns.
        {:ok,
         assign(socket,
           session: Map.take(session, [:title, :model_tier, :updated_at]),
           turns: turns,
           page_title: session.title
         )}

      {:error, :not_found} ->
        {:ok, assign(socket, session: nil, turns: [], page_title: "Research session")}
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mx-auto w-full max-w-5xl px-4 py-8">
      <div :if={is_nil(@session)} class="flex flex-col items-center py-24 text-center">
        <div class="mb-6 flex size-12 items-center justify-center rounded-2xl bg-base-200 text-base-content/70">
          <.icon name="hero-eye-slash" class="size-6" />
        </div>
        <h1 class="text-2xl font-semibold tracking-tight">
          This research session is not available
        </h1>
        <p class="mt-3 max-w-md text-base-content/55">
          The link may be wrong, or the owner may have stopped sharing this session.
        </p>
      </div>

      <div :if={@session} class="space-y-8">
        <header class="border-b border-base-300 pb-4">
          <div class="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-base-content/40">
            <.icon name="hero-beaker" class="size-4" /> Shared research session
          </div>
          <h1 class="mt-2 text-2xl font-semibold tracking-tight">{@session.title}</h1>
          <p class="mt-1 flex items-center gap-2 text-xs text-base-content/50">
            <span>{Calendar.strftime(@session.updated_at, "%b %d, %Y")}</span>
            <span class="rounded-full bg-base-200 px-1.5 py-0.5">{@session.model_tier}</span>
          </p>
        </header>

        <.turn_view :for={turn <- @turns} turn={turn} running={false} />

        <p class="border-t border-base-300 pt-4 text-center text-[11px] text-base-content/40">
          Read-only view · generated by the Santiment deep research agent
        </p>
      </div>
    </div>
    """
  end
end
