// Cache-saturation load test for the GraphQL API.
//
// Unlike graphql_load_test.js (which optimizes for realistic traffic mix),
// this script controls the CACHE HIT RATIO of the request stream so you can
// observe the memory/latency behavior of the Cachex-backed GraphQL cache
// under different hit profiles:
//
//   * "pool" requests draw from a fixed, deterministic pool of
//     (metric, slug, time-window, interval) combinations. The combination is
//     identical across VUs and iterations, so after first touch these are
//     server-side cache HITS.
//   * "fresh" requests shift the time window by a unique per-request number
//     of hours, producing a never-seen-before cache key — a guaranteed MISS
//     that also inserts a new cache entry (this is what saturates the cache).
//
// HIT_RATIO controls the pool/fresh split. Run the three canonical profiles:
//
//   k6 run --env HIT_RATIO=0.9 scripts/cache_saturation_test.js
//   k6 run --env HIT_RATIO=0.5 scripts/cache_saturation_test.js
//   k6 run --env HIT_RATIO=0.1 scripts/cache_saturation_test.js
//
// While it runs, watch the server-side cache from IEx:
//
//   SanbaseWeb.Graphql.Cache.count()  # entries
//   SanbaseWeb.Graphql.Cache.size()   # ETS megabytes
//   :erlang.memory(:total)            # whole-BEAM footprint
//
// Other tunables:
//   SCENARIO   - smoke | load | stress | rate (default: load)
//   RATE       - req/s for SCENARIO=rate (default: 30)
//   DURATION   - duration for SCENARIO=rate (default: 2m)
//   POOL_SIZE  - number of distinct hot combinations (default: 500)
//   DATA_POINTS_PER_QUERY - comma-separated approximate response sizes (data points
//                per request) to mix, default "180,1000,3000". The interval
//                is the metric's minInterval (fetched in setup()) and the
//                from/to window stretches to hit the target, so daily-only
//                metrics cap at MAX_WINDOW_DAYS points.
//   BASE_URL   - target server (default: http://localhost:4000)
//   APIKEY     - API key(s), comma-separated; overrides data/apikeys.json.
//                Use this for remote targets (stage) where the local
//                mix load_test.setup keys don't exist.
//   WARMUP     - "1" primes every pool combination once in setup(), so pool
//                requests are cache hits from the first measured iteration
//                (otherwise first touch of each combo is a miss).

import http from "k6/http";
import { check, sleep } from "k6";
import { SharedArray } from "k6/data";
import { Rate, Trend, Counter } from "k6/metrics";

// Custom metrics — pool (mostly hits) and fresh (guaranteed misses) split
const errorRate = new Rate("graphql_errors");
const poolDuration = new Trend("pool_query_duration", true);
const freshDuration = new Trend("fresh_query_duration", true);
const poolCount = new Counter("pool_requests");
const freshCount = new Counter("fresh_requests");

// API keys: --env APIKEY=<key>[,<key>...] wins; otherwise fall back to the
// JSON file generated by mix load_test.setup (local runs only).
const apikeys = new SharedArray("apikeys", function () {
  if (__ENV.APIKEY) {
    return __ENV.APIKEY.split(",").map((s) => s.trim()).filter(Boolean);
  }
  try {
    return JSON.parse(open("../data/apikeys.json"));
  } catch (_e) {
    return [];
  }
});

if (!Array.isArray(apikeys) || apikeys.length === 0) {
  throw new Error(
    "No API key. Pass --env APIKEY=<key> or run `mix load_test.setup` to generate load_test/data/apikeys.json.",
  );
}

const BASE_URL = __ENV.BASE_URL || "http://localhost:4000";
const GRAPHQL_URL = `${BASE_URL}/graphql`;
const HIT_RATIO = parseFloat(__ENV.HIT_RATIO || "0.9");
const POOL_SIZE = parseInt(__ENV.POOL_SIZE || "500", 10);

if (!(HIT_RATIO >= 0 && HIT_RATIO <= 1)) {
  throw new Error(`Invalid HIT_RATIO="${__ENV.HIT_RATIO}". Use a number in [0, 1].`);
}

const RATE_RPS = parseInt(__ENV.RATE || "30", 10);

const scenarios = {
  smoke: { executor: "constant-vus", vus: 2, duration: "30s" },
  load: { executor: "constant-vus", vus: 20, duration: "2m" },
  stress: {
    executor: "ramping-vus",
    startVUs: 0,
    stages: [
      { duration: "30s", target: 10 },
      { duration: "1m", target: 50 },
      { duration: "1m", target: 50 },
      { duration: "30s", target: 0 },
    ],
  },
  // Fixed requests-per-second regardless of response latency. Preferred for
  // remote targets (stage): load is predictable and easy to keep under the
  // nginx per-IP rate limits.
  rate: {
    executor: "constant-arrival-rate",
    rate: RATE_RPS,
    timeUnit: "1s",
    duration: __ENV.DURATION || "2m",
    preAllocatedVUs: RATE_RPS,
    maxVUs: RATE_RPS * 4,
  },
};

const selectedScenario = __ENV.SCENARIO || "load";
if (!Object.prototype.hasOwnProperty.call(scenarios, selectedScenario)) {
  throw new Error(
    `Invalid SCENARIO="${selectedScenario}". Valid values: ${Object.keys(scenarios).join(", ")}`,
  );
}

export const options = {
  scenarios: { default: scenarios[selectedScenario] },
  setupTimeout: "600s",
  thresholds: {
    http_req_duration: ["p(95)<5000"],
    graphql_errors: ["rate<0.1"],
  },
};

// --- Static data -------------------------------------------------------------

let SLUGS;
try {
  SLUGS = JSON.parse(open("../data/slugs.json"));
} catch (_e) {
  SLUGS = [
    "bitcoin", "ethereum", "solana", "cardano", "chainlink",
    "litecoin", "avalanche", "polkadot-new", "dogecoin", "tron",
    "xrp", "binance-coin", "monero", "stellar", "cosmos",
    "uniswap", "aave", "near-protocol", "aptos", "sui",
  ];
}

const METRICS = [
  "daily_active_addresses",
  "transaction_volume",
  "exchange_inflow",
  "exchange_outflow",
  "network_growth",
  "nvt",
  "mvrv_usd",
  "circulation",
  "age_consumed",
  "velocity",
  "mean_dollar_invested_age",
  "dev_activity_1d",
];

// Approximate response sizes (data points per request) to mix in the run.
// Override with --env DATA_POINTS_PER_QUERY=180,3000.
const DATA_POINTS_PER_QUERY = (__ENV.DATA_POINTS_PER_QUERY || "180,1000,3000")
  .split(",")
  .map((s) => parseInt(s.trim(), 10));

if (DATA_POINTS_PER_QUERY.length === 0 || DATA_POINTS_PER_QUERY.some((n) => !(n > 0))) {
  throw new Error(
    `Invalid DATA_POINTS_PER_QUERY="${__ENV.DATA_POINTS_PER_QUERY}". Use positive integers, comma-separated.`,
  );
}

// Longest allowed from/to window. Bounds both DB scan size and how far a
// coarse (daily) metric can stretch toward a large point target.
const MAX_WINDOW_DAYS = 730;

// Allowed request intervals, finest first. A metric uses the first step not
// finer than its minInterval.
const INTERVAL_STEPS = [
  ["5m", 5],
  ["15m", 15],
  ["30m", 30],
  ["1h", 60],
  ["2h", 120],
  ["4h", 240],
  ["8h", 480],
  ["1d", 1440],
  ["7d", 10080],
];

function parseIntervalToMinutes(str) {
  const m = /^(\d+)([smhdw])$/.exec(str || "");
  if (!m) return 1440; // unknown/missing metadata -> assume daily (coarse, safe)
  const n = parseInt(m[1], 10);
  return { s: n / 60, m: n, h: n * 60, d: n * 1440, w: n * 10080 }[m[2]];
}

// Pick interval + window (days) yielding ~targetPoints for a metric whose
// finest resolution is minMinutes: points = window / interval. Fractional
// days are fine — only the resulting ISO strings must be deterministic.
function windowFor(minMinutes, targetPoints) {
  minMinutes = minMinutes || 1440;
  const step =
    INTERVAL_STEPS.find(([_name, mins]) => mins >= minMinutes) ||
    INTERVAL_STEPS[INTERVAL_STEPS.length - 1];
  const interval = step[0];
  const intervalMinutes = step[1];
  const idealDays = (targetPoints * intervalMinutes) / 1440;
  const days = Math.min(Math.max(idealDays, 1), MAX_WINDOW_DAYS);
  return { interval, days };
}

// --- Deterministic combination pool ------------------------------------------

// combo(i) is a pure function of i: every VU computes the same combination
// for the same index, which is what makes pool requests collide on the same
// server-side cache keys. Mixed-radix decomposition of i so all
// metric×slug×data_points combinations are reachable.
const MAX_DISTINCT_COMBOS = METRICS.length * SLUGS.length * DATA_POINTS_PER_QUERY.length;

function combo(i) {
  const metric = METRICS[i % METRICS.length];
  const slug = SLUGS[Math.floor(i / METRICS.length) % SLUGS.length];
  const target =
    DATA_POINTS_PER_QUERY[Math.floor(i / (METRICS.length * SLUGS.length)) % DATA_POINTS_PER_QUERY.length];
  return { metric, slug, target };
}

// Midnight-aligned `to` so the from/to strings are byte-identical for the
// whole run — the server buckets datetimes by TTL when building cache keys,
// and stable strings guarantee stable keys. minIntervals comes from setup().
function poolQueryArgs(i, minIntervals) {
  const { metric, slug, target } = combo(i);
  const { interval, days } = windowFor(minIntervals[metric], target);
  const to = new Date(Date.now());
  to.setUTCHours(0, 0, 0, 0);
  const from = new Date(to.getTime() - days * 86400 * 1000);

  return {
    metric,
    slug,
    target,
    interval,
    from: from.toISOString(),
    to: to.toISOString(),
  };
}

// Guaranteed-miss window: shift `to` back by a per-request-unique number of
// seconds. Steps are larger than the server's TTL bucket width (~10 min), so
// no two shifts can collapse into the same bucketed cache key. Shifts wrap
// after ~45k fresh requests per run; raise SHIFT_STEP_S coverage if you run
// longer scenarios.
const SHIFT_STEP_S = 700;
const YEAR_S = 365 * 86400;

function freshQueryArgs(minIntervals) {
  // Compact per-request-unique nonce (holds while a VU stays under 10k iters)
  const nonce = (__VU - 1) * 10_000 + __ITER;
  const shiftS = ((nonce * SHIFT_STEP_S) % YEAR_S) + 3600;
  const { metric, slug, target } = combo(nonce % POOL_SIZE);
  const { interval, days } = windowFor(minIntervals[metric], target);

  const to = new Date(Date.now() - shiftS * 1000);
  const from = new Date(to.getTime() - days * 86400 * 1000);

  return {
    metric,
    slug,
    target,
    interval,
    from: from.toISOString(),
    to: to.toISOString(),
  };
}

function buildQuery({ metric, slug, from, to, interval }) {
  return `{
    getMetric(metric: "${metric}") {
      timeseriesData(
        selector: { slug: "${slug}" }
        from: "${from}"
        to: "${to}"
        interval: "${interval}"
      ) {
        datetime
        value
      }
    }
  }`;
}

// --- Setup: metric resolutions + optional warmup -------------------------------

// WARMUP=1 primes every pool combination once so pool requests are
// server-side cache hits from the first measured iteration. Without warmup
// the observed hit ratio starts below HIT_RATIO and converges as the pool
// gets touched.
const WARMUP = __ENV.WARMUP === "1" || __ENV.WARMUP === "true";
const WARMUP_BATCH = 10;

export function setup() {
  // Warn here rather than in the init context — init re-runs per VU and
  // would repeat the message; setup() runs exactly once.
  if (POOL_SIZE > MAX_DISTINCT_COMBOS) {
    console.warn(
      `POOL_SIZE=${POOL_SIZE} exceeds the ${MAX_DISTINCT_COMBOS} distinct ` +
        `metric/slug/data-points combinations ` +
        `(${METRICS.length} metrics x ${SLUGS.length} slugs x ` +
        `${DATA_POINTS_PER_QUERY.length} response sizes); ` +
        `effective pool is ${MAX_DISTINCT_COMBOS} distinct cache keys.`,
    );
  }

  const apikey = apikeys[0];
  const headers = {
    "Content-Type": "application/json",
    Authorization: `Apikey ${apikey}`,
  };

  // metric -> minInterval in minutes, all metrics in one aliased query
  const aliased = METRICS.map(
    (m, idx) => `m${idx}: getMetric(metric: "${m}") { metadata { minInterval } }`,
  ).join("\n");
  const res = http.post(GRAPHQL_URL, JSON.stringify({ query: `{ ${aliased} }` }), {
    headers,
  });

  const minIntervals = {};
  try {
    const data = JSON.parse(res.body).data || {};
    METRICS.forEach((m, idx) => {
      minIntervals[m] = parseIntervalToMinutes(data[`m${idx}`]?.metadata?.minInterval);
    });
  } catch (_e) {
    console.warn(
      "minInterval fetch failed; assuming daily resolution for all metrics",
    );
    METRICS.forEach((m) => {
      minIntervals[m] = 1440;
    });
  }
  console.log(
    "minInterval (minutes): " +
      METRICS.map((m) => `${m}=${minIntervals[m]}`).join(", "),
  );

  if (WARMUP) {
    const effectivePool = Math.min(POOL_SIZE, MAX_DISTINCT_COMBOS);
    console.log(`Warmup: priming ${effectivePool} pool combinations...`);

    for (let start = 0; start < effectivePool; start += WARMUP_BATCH) {
      const batch = [];
      for (let i = start; i < Math.min(start + WARMUP_BATCH, effectivePool); i++) {
        batch.push([
          "POST",
          GRAPHQL_URL,
          JSON.stringify({ query: buildQuery(poolQueryArgs(i, minIntervals)) }),
          { headers },
        ]);
      }
      http.batch(batch);
    }

    console.log("Warmup complete.");
  }

  return { minIntervals };
}

// --- Main --------------------------------------------------------------------

export default function (data) {
  const apikey = apikeys[(__VU - 1) % apikeys.length];

  const isPool = Math.random() < HIT_RATIO;
  const args = isPool
    ? poolQueryArgs(Math.floor(Math.random() * POOL_SIZE), data.minIntervals)
    : freshQueryArgs(data.minIntervals);
  const query = buildQuery(args);

  const keyClass = isPool ? "pool" : "fresh";

  const res = http.post(GRAPHQL_URL, JSON.stringify({ query }), {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Apikey ${apikey}`,
    },
    tags: { key_class: keyClass, data_points: String(args.target) },
  });

  if (isPool) {
    poolCount.add(1);
    poolDuration.add(res.timings.duration);
  } else {
    freshCount.add(1);
    freshDuration.add(res.timings.duration);
  }

  const success = check(
    res,
    {
      "status is 200": (r) => r.status === 200,
      "no errors in body": (r) => {
        try {
          const body = JSON.parse(r.body);
          return !body.errors || body.errors.length === 0;
        } catch (_e) {
          return false;
        }
      },
    },
    { key_class: keyClass },
  );

  errorRate.add(!success);

  // The arrival-rate executor paces iterations itself; sleeping would only
  // hold VUs busy and force extra allocations.
  if (selectedScenario !== "rate") {
    sleep(Math.random() * 0.2 + 0.05);
  }
}
