version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - CI=true
      - REACT_APP_WEBSITE_URL=https://app-stage.santiment.net
    command: yarn test --ci
  frontend:
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    command: /bin/bash -c "npm run start:light" # The command to run in when the container starts
