version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    tty: true
    stdin_open: true
    command: yarn test --watchAll
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - CI=true
    command: yarn test --ci
