defmodule SanbaseWeb.GenericAdmin.SocialVolumeQuery do
  @behaviour SanbaseWeb.GenericAdmin
  def schema_module, do: Sanbase.Project.SocialVolumeQuery
  def resource_name, do: "social_volume_queries"
  def singular_resource_name, do: "social_volume_query"

  def resource() do
    %{
      actions: [:new, :edit],
      preloads: [:project],
      new_fields: [:project, :query, :autogenerated_query],
      edit_fields: [:project, :query, :autogenerated_query],
      belongs_to_fields: %{
        project: SanbaseWeb.GenericAdmin.belongs_to_project()
      },
      fields_override: %{
        project_id: %{
          value_modifier: &SanbaseWeb.GenericAdmin.Project.project_link/1
        }
      }
    }
  end
end
