defmodule Sanbase.ExternalServices.IcoSpreadsheet.IcoSpreadsheetRow do
  defstruct [
    :project_name,
    :ticker,
    :ico_start_date,
    :ico_end_date,
    :tokens_issued_at_ico,
    :tokens_sold_at_ico,
    :tokens_team,
    :usd_btc_icoend,
    :funds_raised_btc,
    :usd_eth_icoend,
    :ico_currencies,
    :ico_contributors,
    :highest_bonus_percent_for_ico,
    :bounty_campaign,
    :percent_tokens_for_bounties,
    :minimal_cap_amount,
    :minimal_cap_archived,
    :maximal_cap_amount,
    :maximal_cap_archived,
    :market_segment,
    :infrastructure,
    :team_website,
    :team_linkedin_available,
    :avno_linkedin_network_team,
    :team_country_origins,
    :team_dev_people,
    :team_business_people,
    :team_real_names,
    :team_pics_availabe,
    :team_advisors,
    :advisor_linkedin_available,
    :av_no_linkedin_network_advisors,
    :geolocation,
    :geolocation_city,
    :website_link,
    :open_source,
    :github_link,
    :github_commits,
    :github_contributors,
    :wp_available,
    :wp_link,
    :wp_authors,
    :wp_pages,
    :wp_citations,
    :btt_link,
    :btt_date,
    :btt_total_reads,
    :btt_post_until_icostart,
    :btt_post_until_icoend,
    :btt_posts_total,
    :twitter_link,
    :twitter_joindate,
    :twitter_tweets,
    :twitter_follower,
    :twitter_following,
    :twitter_likes,
    :facebook_link,
    :facebook_likes,
    :reddit_link,
    :reddit_subscribers,
    :eth_wallets,
    :btc_wallets
  ]

  def get_column_indices do
    %{
      project_name: 1,
      ticker: 2,
      ico_start_date: 15,
      ico_end_date: 16,
      tokens_issued_at_ico: 22,
      tokens_sold_at_ico: 23,
      tokens_team: 24,
      usd_btc_icoend: 28,
      funds_raised_btc: 29,
      usd_eth_icoend: 30,
      ico_currencies: 32,
      ico_contributors: 35,
      highest_bonus_percent_for_ico: 36,
      bounty_campaign: 37,
      percent_tokens_for_bounties: 38,
      minimal_cap_amount: 40,
      minimal_cap_archived: 41,
      maximal_cap_amount: 43,
      maximal_cap_archived: 44,
      market_segment: 45,
      infrastructure: 52,
      team_website: 63,
      team_linkedin_available: 64,
      avno_linkedin_network_team: 65,
      team_country_origins: 67,
      team_dev_people: 71,
      team_business_people: 73,
      team_real_names: 75,
      team_pics_availabe: 76,
      team_advisors: 78,
      advisor_linkedin_available: 79,
      av_no_linkedin_network_advisors: 80,
      geolocation: 81,
      geolocation_city: 85,
      website_link: 86,
      open_source: 95,
      github_link: 96,
      github_commits: 97,
      github_contributors: 98,
      wp_available: 99,
      wp_link: 100,
      wp_authors: 101,
      wp_pages: 102,
      wp_citations: 103,
      btt_link: 105,
      btt_date: 106,
      btt_total_reads: 108,
      btt_post_until_icostart: 110,
      btt_post_until_icoend: 111,
      btt_posts_total: 112,
      twitter_link: 115,
      twitter_joindate: 116,
      twitter_tweets: 117,
      twitter_follower: 119,
      twitter_following: 121,
      twitter_likes: 124,
      facebook_link: 126,
      facebook_likes: 127,
      reddit_link: 129,
      eth_wallet: 137,
      btc_wallet: 138,
      btc_wallet2: 139,
      btc_wallet3: 140,
      btc_wallet4: 141,
      btc_wallet5: 142,
      reddit_subscribers: 147
    }
  end
end
