defmodule Sanbase.FileStore do
  use Waffle.Definition

  @versions [:original, :w400, :w800, :w1200, :w2000]
  @acl :public_read
  @extension_whitelist ~w(.jpg .jpeg .gif .png .pdf .csv .mp4)
  @image_extensions ~w(.jpg .jpeg .gif .png)
  # Files that are downloaded rather than rendered inline in the browser
  @download_extensions ~w(.pdf .csv)
  @max_file_size 10 * 1024 * 1024
  @admin_max_file_size 50 * 1024 * 1024
  @cache_max_age 2_592_000

  @variant_versions [:w400, :w800, :w1200, :w2000]

  def allowed_extensions(), do: @extension_whitelist
  def allowed_file_size(), do: div(max_file_size(), 1024 * 1024)

  @doc ~s"""
  Validate the file size and extension.

  On the admin pod the allowed file size is bigger to uploading
  bigger reports while not allowing users to upload too big images.
  """
  def validate({file, _}) do
    cond do
      not allowed_extension?(file) -> {:error, "invalid_extension"}
      in_memory_file?(file) -> true
      not allowed_size?(file) -> {:error, "file_too_large"}
      true -> true
    end
  end

  def transform(version, {file, _scope}) when version in @variant_versions do
    ext = file.file_name |> Path.extname() |> String.downcase()

    if ext in @image_extensions do
      width = version |> Atom.to_string() |> String.trim_leading("w")
      {:convert, "-strip -resize #{width}x> -quality 85"}
    else
      :skip
    end
  end

  # Waffle.Definition injects a `transform(_, _) -> :noaction` fallback clause
  # which covers the non-variant versions (:original).

  @doc ~s"""
    Generate a filename. The generated file name is in the format `scope_timestamp_name`
    where scope is explicitly passed from outside. That can be some randomly generated
    string, the hash of the file or something else.

    For variant versions (w400, w800, etc.), the version is prepended to the filename.
  """
  def filename(:original, {file, scope}) do
    file_name = Path.basename(file.file_name, Path.extname(file.file_name))
    "#{scope}_#{file_name}"
  end

  def filename(version, {file, scope}) do
    file_name = Path.basename(file.file_name, Path.extname(file.file_name))
    "#{version}_#{scope}_#{file_name}"
  end

  @doc ~s"""
  Headers stored alongside the S3 object.

  Non-image files are served as downloads, so a `content-disposition` header with
  a human readable file name is attached to them. Without it browsers name the
  downloaded file after the object key, which is prefixed with the content hash
  and the upload timestamp.

  Images are left without a disposition header so they can still be rendered
  inline.
  """
  def s3_object_headers(_version, {file, _scope}) do
    headers = [cache_control: "max-age=#{@cache_max_age}"]

    case content_disposition(file.file_name) do
      nil -> headers
      disposition -> [{:content_disposition, disposition} | headers]
    end
  end

  @doc ~s"""
  Build the `content-disposition` header value for a stored file name, or nil if
  the file is not one that is served as a download.
  """
  def content_disposition(stored_filename) do
    extension = stored_filename |> Path.extname() |> String.downcase()

    if extension in @download_extensions do
      filename = download_filename(stored_filename)

      # The quoted `filename` is the ASCII-only fallback for clients that do not
      # support RFC 5987, `filename*` carries the original UTF-8 name.
      ascii_fallback = String.replace(filename, ~r/[^\x20-\x7E]|["\\]/u, "_")
      encoded = URI.encode(filename, &URI.char_unreserved?/1)

      ~s|attachment; filename="#{ascii_fallback}"; filename*=UTF-8''#{encoded}|
    end
  end

  @doc ~s"""
  Strip the generated prefixes from a stored file name and return the original
  name the file was uploaded with.

  Stored names look like `w400_<content hash>_<unix millis>_original_name.pdf`.
  All three prefixes are generated by us and are noise to whoever downloads the
  file.
  """
  def download_filename(stored_filename) do
    stored_filename
    |> Path.basename()
    |> String.replace(~r/^w\d+_/, "")
    |> String.replace(~r/^[0-9a-fA-F]{32,}_/, "")
    |> String.replace(~r/^\d{10,16}_/, "")
  end

  # Helper functions

  defp allowed_extension?(file) do
    extension = file.file_name |> Path.extname() |> String.downcase()
    Enum.member?(@extension_whitelist, extension)
  end

  defp max_file_size() do
    if System.get_env("CONTAINER_TYPE") in ["all", "admin"] do
      @admin_max_file_size
    else
      @max_file_size
    end
  end

  defp allowed_size?(file) do
    max_file_size = max_file_size()

    case File.stat(file.path) do
      {:ok, %{size: size}} when size <= max_file_size -> true
      _ -> false
    end
  end

  defp in_memory_file?(file) do
    !file.path
  end
end
