defmodule Sanbase.Repo.Migrations.ExtendSocialVolumeQueryTable do
  @moduledoc false
  use Ecto.Migration

  def change do
    alter table(:project_social_volume_query) do
      add(:autogenerated_query, :text)
    end
  end
end
