defmodule Sanbase.Repo.Migrations.AddSanbaseNotificationsTable do
  use Ecto.Migration

  @notifications_table :sanbase_notifications
  def change do
    create table(@notifications_table) do
      # Core notification fields
      add(:type, :string, null: false)
      add(:title, :text)
      add(:content, :text)

      # Who created the notification (nullable for broadcast notifications)
      # This is not who the notification will be shown to. This is the user
      # who made the action (comment, vote, publish) that sparked the notification.
      # The receiver of the notification is stored in the sanbase_notifications_read_status
      # table, one row per receiver (mostly the followers of the user who made the action).
      # So it's more important to have index on that other table for querying notifications for a user.
      add(:user_id, references(:users, on_delete: :delete_all))

      # Entity reference (flexible, no explicit foreign keys)
      add(:entity_id, :bigint)
      add(:entity_name, :text)
      add(:entity_type, :string)

      # Notification management
      add(:is_system_generated, :boolean, default: false, null: false)

      # A broadcast notification is a notification that is sent to all users.
      # A system generated notification is a notification that is generated by the system.
      # There is one record with user_id = null and is_broadcast = true for each notification.
      # Because of that, the read_at is tracked per user in the sanbase_notifications_read_status table.
      add(:is_broadcast, :boolean, default: false, null: false)

      # The grouping key *might* be used to group notifications together.
      # For example, if you want to group all notifications about a new feature into a single notification.
      add(:grouping_key, :string)

      # Additional flexible data storage
      add(:json_data, :map)

      add(:is_deleted, :boolean, default: false, null: false)

      timestamps()
    end

    create table(:sanbase_notifications_read_status) do
      add(:user_id, references(:users, on_delete: :delete_all), null: false)

      add(:notification_id, references(:sanbase_notifications, on_delete: :delete_all),
        null: false
      )

      # By default it is nil, meaning the notification is unread.
      add(:read_at, :utc_datetime, null: true, default: nil)

      timestamps()
    end

    create(unique_index(:sanbase_notifications_read_status, [:user_id, :notification_id]))
  end
end
