defmodule Sanbase.Repo.Migrations.AddSanbaseNotificationsTable do
  use Ecto.Migration

  def change do
    create table(:sanbase_notifications) do
      # Core notification fields
      add(:type, :string, null: false)
      add(:title, :text)
      add(:content, :text)

      # User relationships
      add(:user_id, references(:users, on_delete: :delete_all))

      # Entity reference (flexible, no explicit foreign keys)
      add(:entity_type, :string)
      add(:entity_id, :integer)

      # Notification management
      add(:is_system_generated, :boolean, default: false, null: false)
      # A broadcast notification is a notification that is sent to all users.
      # A system generated notification is a notification that is generated by the system.
      # There is one record with user_id = null and is_broadcast = true for each notification.
      # Because of that, the read_at is tracked per user in the sanbase_notifications_read_status table.
      add(:is_broadcast, :boolean, default: false, null: false)

      # The grouping key *might* be used to group notifications together.
      # For example, if you want to group all notifications about a new feature into a single notification.
      add(:grouping_key, :string)

      # Additional flexible data storage
      add(:json_data, :map)

      add(:is_deleted, :boolean, default: false, null: false)

      timestamps()
    end

    create table(:sanbase_notifications_read_status) do
      # A broadcast notification is a notification that is sent to all users.
      # A system generated notification is a notification that is generated by the system.
      # There is one record with user_id = null and is_broadcast = true for each notification.
      # Because of that, the read_at is tracked per user in the sanbase_notification_user_reads table.
      add(:user_id, references(:users, on_delete: :delete_all), null: false)

      add(:notification_id, references(:sanbase_notifications, on_delete: :delete_all),
        null: false
      )

      add(:read_at, :utc_datetime, null: false)
    end

    create(unique_index(:sanbase_notifications_read_status, [:user_id, :notification_id]))
  end
end
