Sanbase.Seeds.BurnRateSeed.populate()
Sanbase.Seeds.DailyActiveAddressesSeed.populate()
Sanbase.Seeds.TransactionVolumeSeed.populate()
Sanbase.Seeds.ExchangeFundsFlowSeed.populate()
Sanbase.Seeds.TokenCirculationSeed.populate()
